import 'package:restaurant/menuItem.dart';
import 'package:restaurant/restaurantOrder.dart';

List<MenuItem> menuDishes = [
   MenuItem(name:"Margherita Pizza",
      details:"Classic pizza topped with tomato sauce, fresh mozzarella, and basil leaves.",
      price: 17,
      imageName: "pizza", updateOrder: (RestaurantOrder ) {  }, order: RestaurantOrder(orderId: '', dishes: []), itemType: ItemType.main,),
   MenuItem(name:"Spaghetti",
      details:"Spaghetti tossed in a fresh tomato sauce with olives, black pepper and basil leaves.",
      price: 15.50,
      imageName: "pasta", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.main,),
   MenuItem(name:"Italian Wedge Salad",
      details:"Iceberg lettuce, cherry tomatoes, red onions, Gorgonzola, and Italian dressing.",
      price: 8.50,
      imageName: "salad", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.main,),
   MenuItem(name:"Risotto ai Funghi",
      details:"Creamy risotto cooked with porcini mushrooms, onions, white wine, and Parmigiano-Reggiano cheese.",
      price: 19.50,
      imageName: "risotto", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.main,),
   MenuItem(name:"Tiramisu",
      details:"Layers of coffee-soaked ladyfingers and mascarpone cheese dusted with cocoa powder.",
      price: 11,
      imageName: "tiramisu", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.dessert,),
   MenuItem(name:"Zeppole",
      details:"Light and fluffy fried dough balls, dusted with powdered sugar.",
      price: 5.00,
      imageName: "zeppole", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.dessert,),
   MenuItem(name:"Lemon Cake",
      details:"Traditional Italian fluffy lemon cake with fresh mint and powdered sugar on top.",
      price: 6.50,
      imageName: "lemon_cake", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.dessert,),
   MenuItem(name:"Negroni",
      details:"A classic Italian cocktail made with equal parts gin, Campari, and sweet vermouth, garnished with an orange slice.",
      price: 7.50,
      imageName: "negroni", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.drink,),
   MenuItem(name:"Cappuccino",
      details:"Espresso topped with steamed milk and a layer of frothy milk foam.",
      price: 4.50,
      imageName: "capuccino", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.drink,),
   MenuItem(name:"Limoncello",
      details:"A lemon-flavored liqueur, served chilled as a digestif.",
      price: 8,
      imageName: "limoncello", updateOrder: (RestaurantOrder ) {  },order: RestaurantOrder(orderId: '', dishes: []),itemType: ItemType.drink,),
];